version: "3.9"

services: 
    nginx:
        image: nginx:stable
        restart: always
        ports:
        - "3000:8080"
        volumes:
          - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    app1:
        ports: 
            - "3001:3000"
        environment: 
            - APPID=app1
        image: demoapp
    app2:
        ports: 
            - "3002:3000"
        environment: 
            - APPID=app2
        image: demoapp
    app3:
        ports: 
            - "3003:3000"
        environment: 
            - APPID=app3
        image: demoapp
    app4:
        ports: 
            - "3004:3000"
        environment: 
            - APPID=app4
        image: demoapp