version: '3.2'

services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - '8030:8030'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    networks:
      - node_demo
  app1:
    # ports:
    #   - '3001:3000'
    environment:
      - APPID=app1
    image: demoapp1
    container_name: app1
    networks:
      - node_demo
  app2:
    # ports:
    #   - '3002:3000'
    environment:
      - APPID=app2
    image: demoapp1
    container_name: app2
    networks:
      - node_demo
  app3:
    # ports:
    #   - '3003:3000'
    environment:
      - APPID=app3
    image: demoapp1
    container_name: app3
    networks:
      - node_demo
  app4:
    # ports:
    #   - '3004:3000'
    environment:
      - APPID=app4
    image: demoapp1
    container_name: app4
    networks:
      - node_demo
networks:
  node_demo:
